### Question 1
a) Using Numpy for inputs A

b) Using TensorFlow2 with inputs B


In [1]:
import numpy as np

In [2]:
x_a = np.array(([0.4032, 0.4583]), dtype=float)
y_a = np.array(([0.62]), dtype=float)

In [3]:
# Class
class ANN(object):
    
    # constructor, set up weights
    def __init__(self):
        #Weights (we are using two layers here), weights are pre set from example two in the notes
        self.W1 = np.array(([1.23,0.34,-3.71],
                            [-0.58,1.07,-0.65]), dtype=float) 
        self.W2 = np.array(([0.66],
                            [1.25],
                            [-1.02]), dtype=float)
    
    #sigmoid function
    def sigmoid(self, valuesIN):
        return 1/(1+np.exp(-valuesIN))
    
    #forward steps (remember slide 54)
    def forward(self, inputsX):
        # feedforward propagation
        self.Zi = np.dot(inputsX, self.W1)     # Step 1
        self.Ai = self.sigmoid(self.Zi)        # Step 2
        self.Z4 = np.dot(self.Ai, self.W2)     # Step 3
        y_Hat = self.sigmoid(self.Z4)          # Step 4
        return y_Hat

In [4]:
NN = ANN()
y_Hat = NN.forward(x_a)
print(y_Hat)

# back to sclae
print("Predicted Score:",round(y_Hat[0] * 100,2),"%")
print("Loss: \n" + str(np.mean(np.square(y_a - NN.forward(x_a)))))

[0.73831593]
Predicted Score: 73.83 %
Loss: 
0.013998660001847537


In [5]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

seed = 1
# fix random seed for reproducibility
np.random.seed(seed)
tf.random.set_seed(seed)


# Single Instance Input
X = np.array(([[0.6129, 0.5]]), dtype=float)
# Single Instance Output
y = np.array(([0.78]), dtype=float)

model = Sequential()
model.add(Dense(3, input_dim=2, activation='sigmoid', use_bias = False))
model.add(Dense(1, activation='sigmoid', use_bias = False))
model.compile(loss='mse', metrics=['acc'])


W1 = [np.array(([[1.23,0.34,-3.71],
               [-0.58,1.07,-0.65]]), dtype=float)]
W2 = [np.array(([0.66],
               [1.25],
               [-1.02]), dtype=float)]

print("Randomly assigned initial weights:")
print("\nFirst layer :", model.layers[0].get_weights())
print("\nSecond layer:", model.layers[1].get_weights())

print("\n\nAssigning new weights:")
model.layers[0].set_weights(W1)
model.layers[1].set_weights(W2)

print("\nFirst layer :", model.layers[0].get_weights())
print("\nSecond layer:", model.layers[1].get_weights())



print("\n\nPrediction y_hat =", model.predict(X)[0][0])

result = model.fit(X,y, verbose = 0)
print("Loss             =", result.history["loss"][0])

Randomly assigned initial weights:

First layer : [array([[-0.73366153,  0.8796015 ,  0.28695   ],
       [-0.14340228, -0.4558388 ,  0.3122064 ]], dtype=float32)]

Second layer: [array([[ 0.02475715],
       [-0.13831842],
       [-0.2240473 ]], dtype=float32)]


Assigning new weights:

First layer : [array([[ 1.23,  0.34, -3.71],
       [-0.58,  1.07, -0.65]], dtype=float32)]

Second layer: [array([[ 0.66],
       [ 1.25],
       [-1.02]], dtype=float32)]


Prediction y_hat = 0.7652656
Loss             = 0.00021710217697545886


### Question 2

In [6]:
x2 = np.array(([0.5726, 0.5833]), dtype=float)
y2 = np.array(([0.75]), dtype=float)

In [7]:
class ANN2(object):
    
    # constructor, set up weights
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
        #Weights (we are using two layers here), weights are random
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) 
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize)
    
    #sigmoid function
    def sigmoid(self, valuesIN):
        return 1/(1+np.exp(-valuesIN))
    
    #forward steps (remember slide 54)
    def forward(self, inputsX):
        # feedforward propagation
        self.Zi = np.dot(inputsX, self.W1)     # Step 1
        self.Ai = self.sigmoid(self.Zi)        # Step 2
        self.Z4 = np.dot(self.Ai, self.W2)     # Step 3
        y_Hat = self.sigmoid(self.Z4)          # Step 4
        return y_Hat

In [8]:
best_W1= None
best_W2= None
lowest_E = None
pred_G = None

for i in range(1000):
  test = ANN2()
  y_Hat = test.forward(x2)
  loss = (0.5 * (np.square(y2[0] - y_Hat[0])))
  pred = round(y_Hat[0] * 100,2)

  if(not lowest_E):
    lowest_E = loss
    best_W1 = test.W1
    best_W2 = test.W2
    pred_G = pred
  elif(loss < lowest_E):
    lowest_E = loss
    best_W1 = test.W1
    best_W2 = test.W2
    pred_G = pred
    
print("Prediction: ", pred_G)
print("Best Weight 1: ", best_W1)
print("Best Weight 2: ", best_W2)
print("Lowest Loss:", lowest_E)

Prediction:  75.01
Best Weight 1:  [[-0.19136957  1.26051568  0.49889451]
 [ 1.41000386  0.41530106  0.39195774]]
Best Weight 2:  [[-0.2223965 ]
 [ 1.43540371]
 [ 0.33472212]]
Lowest Loss: 9.882363776182445e-09


### Question 3

In [9]:
### FOR TESTING THE BEST WEIGHT AND LOWEST LOSS
class ANN3(object):
    
    # constructor, set up weights
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
        #Weights (we are using two layers here), weights are random
        self.W1 = best_W1
        self.W2 = best_W2
    
    #sigmoid function
    def sigmoid(self, valuesIN):
        return 1/(1+np.exp(-valuesIN))
    
    #forward steps (remember slide 54)
    def forward(self, inputsX):
        # feedforward propagation
        self.Zi = np.dot(inputsX, self.W1)     # Step 1
        self.Ai = self.sigmoid(self.Zi)        # Step 2
        self.Z4 = np.dot(self.Ai, self.W2)     # Step 3
        y_Hat = self.sigmoid(self.Z4)          # Step 4
        return y_Hat

In [11]:
test2 = ANN3()
y_Hat = test2.forward(x2)
print(y_Hat)

# back to scale
print("Predicted Score:",round(y_Hat[0] * 100,2),"%")
print("Loss:", (0.5 * (np.square(y2[0] - y_Hat[0]))))

[0.75014059]
Predicted Score: 75.01 %
Loss: 9.882363776182445e-09


### Extra Test
Run the model using the other instances/rows from question 1.

Print out the predictions and errors. 

In [10]:
x = np.array(([0.4032, 0.4583]), dtype=float)
y = np.array(([0.62]), dtype=float)

best_W1= None
best_W2= None
lowest_E = None
pred_G = None

for i in range(1000):
  test = ANN2()
  y_Hat = test.forward(x)
  loss = (0.5 * (np.square(y[0] - y_Hat[0])))
  pred = round(y_Hat[0] * 100,2)

  if(not lowest_E):
    lowest_E = loss
    best_W1 = test.W1
    best_W2 = test.W2
    pred_G = pred
  elif(loss < lowest_E):
    lowest_E = loss
    best_W1 = test.W1
    best_W2 = test.W2
    pred_G = pred
    
print("Prediction: ", pred_G)
print("Best Weight 1: ", best_W1)
print("Best Weight 2: ", best_W2)
print("Lowest Loss:", lowest_E)

Prediction:  62.0
Best Weight 1:  [[-1.60355569  0.80990376  0.53743833]
 [ 0.23270918  0.15993397  0.72061341]]
Best Weight 2:  [[-0.9358322 ]
 [-0.43003938]
 [ 1.72359101]]
Lowest Loss: 1.0679285492102985e-09


In [13]:
x = np.array(([0.6774, 0.6250]), dtype=float)
y = np.array(([0.8]), dtype=float)

best_W1= None
best_W2= None
lowest_E = None
pred_G = None

for i in range(1000):
  test = ANN2()
  y_Hat = test.forward(x)
  loss = (0.5 * (np.square(y[0] - y_Hat[0])))
  pred = round(y_Hat[0] * 100,2)

  if(not lowest_E):
    lowest_E = loss
    best_W1 = test.W1
    best_W2 = test.W2
    pred_G = pred
  elif(loss < lowest_E):
    lowest_E = loss
    best_W1 = test.W1
    best_W2 = test.W2
    pred_G = pred
    
print("Prediction: ", pred_G)
print("Best Weight 1: ", best_W1)
print("Best Weight 2: ", best_W2)
print("Lowest Loss:", lowest_E)

Prediction:  80.1
Best Weight 1:  [[-0.27718857  0.72941895  1.72903811]
 [ 0.43021491 -0.12713907 -1.29533518]]
Best Weight 2:  [[0.21287157]
 [1.18634202]
 [0.96308258]]
Lowest Loss: 5.47958045842439e-07


In [14]:
x = np.array(([0.6129, 0.5]), dtype=float)
y = np.array(([0.78]), dtype=float)

best_W1= None
best_W2= None
lowest_E = None
pred_G = None

for i in range(1000):
  test = ANN2()
  y_Hat = test.forward(x)
  loss = (0.5 * (np.square(y[0] - y_Hat[0])))
  pred = round(y_Hat[0] * 100,2)

  if(not lowest_E):
    lowest_E = loss
    best_W1 = test.W1
    best_W2 = test.W2
    pred_G = pred
  elif(loss < lowest_E):
    lowest_E = loss
    best_W1 = test.W1
    best_W2 = test.W2
    pred_G = pred
    
print("Prediction: ", pred_G)
print("Best Weight 1: ", best_W1)
print("Best Weight 2: ", best_W2)
print("Lowest Loss:", lowest_E)

Prediction:  78.12
Best Weight 1:  [[ 0.06572179 -1.32810763  0.0787641 ]
 [ 0.24671416 -0.1719782   1.07995358]]
Best Weight 2:  [[-0.20166709]
 [ 1.24471637]
 [ 1.58914964]]
Lowest Loss: 6.828916684876675e-07
